project:
  type: website
  output-dir: docs
website:
  title: "Angelina Evans DPSG Blog"
  navbar:
    background: "purple"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/1AngelinaEvans
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/angelina-evans/ 
format:
  html:

    theme: cosmo
    css: styles.css
    backgroundcolor: "#f1eef6"
    
    

editor: visual

