
---
title: "Week 3 Blog" 
author: "Angelina Evans"
date: "2023-05-31"
categories: "Week Three"
---

# Week 3

## Project Progress

This week, our group was able to time thinking and talking about:

-   Our takeaways from last week's client meeting

-   Project goals

-   Methods to use when working to reach project goals

-   New ideas to add into our project

-   Recurring concerns

Addressing the points above as a group allowed me to get a better idea of our project goals and the directions we should take.

## Web Scraping

One hope for the project is that we can web scrape from housing assessor websites such as [Iowa Assessors](https://iowaassessors.com/) and [Trulia](https://www.trulia.com/). If we are able to successfully do so, we can use images of houses and other information to train our AI model. I focused on learning more about web scraping using R through the DataCamp Course called Web Scraping in R. Before that I also worked on the Intermediate R course to better understand what can be done with R.

I also began to start the web scraping process using R.

## Things That are Going Well

One of my hopes from week 2 was that I would get better with editing and updating blogs. Now I feel a bit more comfortable with the blogs and things are working better for me.

I also think that my group has a good idea of what we should get done. We were also able to come up with steps (ex. creating trials for our AI model that would be easier to troubleshoot).

## Things to Work On

I definitely want to make more progress with web scraping because that is a key part of the project.
